### ISSUE TITLE
Some batch bald results are already labelled

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/superpixel-classification#18]
I have a two-image project where I have labelled around 810 superpixels.  When running training on this with batch bald as the certainty metric, the "least certain" superpixel is one that I have already labelled.  In this instance, a confidence of 0.8989 was reported, but the certainty metric value was reported as -0.2931.  I'd expect that superpixels I've already labelled would not appear in the list.

**Comment by Leengit** [comment]
That sounds like my code.  I'll take a lookl

**Comment by Leengit** [comment]
A design question.  Do we want
1. the class object returned by `al_bench.factory.ComputeCertainty()` to mark already labeled samples as more certain than currently unlabeled samples, so that `HistomicsUI` code can directly offer the lowest-certainty samples to the user for guided labeling without having to separately track which have already been labeled, or
2. the class object returned by `al_bench.factory.ComputeCertainty()` to return actual certainties (e.g., `confidence`, `margin`, `negative_entropy`, and/or `batchbald`) even for the already labeled samples so that the user who is viewing a superpixel's certainty information sees the actual certainty even when the user has already labeled the superpixel?

Regardless of the approach the class object returned by `al_bench.factory.ComputeCertainty()` will need to know which superpixels have already been labeled, at least in the `batchbald` case so that it won't waste valuable slots on already labeled superpixels.

**Comment by manthey** [comment]
We are currently driving the UI with the values in `certainty`.  Marking this as more certain than all unlabeled samples has the virtue of making it so the UI doesn't change, but the drawback that the meaning of the value is less clear.  One way around this would be to add a singular entry to the `certainty_info` dictionary of `labeled_offset` with the amount we offset the pre-labeled samples (or maybe, if the certainty values range doesn't include the origin we would also want a `labeled_minimum`, too); then if we cared to we could reconstruct the actual certainty (or, in the UI, never show anything greater than that minimum).  The drawback of not changing the UI is that showing the certainty of samples labeled in previous epoch is no longer a useful piece of information for a user trying to decide how well the model performs.  The UI could use the labeled_offset and labeled_minimum values to correct for this, though.

Equally valid, would be to add another entry `labeled` which would be an array of booleans just listing whether the sample was labeled.  The UI would then exclude these from the list of samples to label.  This necessitates a UI change, but wouldn't be hard.  The drawback to this approach is that we increase the data volume (conceptually 1 bit per sample but practically we are probably using an int-size memory block for each sample).

Which of the two approaches is done comes down to what is more convenient and maintainable for @Leengit to implement, which may have more to do with how labeled samples are excluded from batchbald computation that anything else.

**Comment by Leengit** [comment]
> Equally valid, would be to add another entry `labeled` which would be an array of booleans just listing whether the sample was labeled.

Perhaps `labeled` would be redundant.  We already have a label number for each superpixel, or a label of `0` to indicate unlabeled.  At least that's the case by the time we get to `superpixel-classification`.  Maybe the UI can simply check whether `label==0` and then skip over suggesting that superpixel for guided labeling whenever that test fails.  (Checking `label==0` is how I envision the implementation within `al_bench`'s `batchbald` functionality — we'll give superpixels for consideration by `batchbald` only if that test passes — so, if `label!=0` is not equivalent to `labeled` then I need to know that for `al_bench` too!)

I am leaning towards this approach of asking the UI to guide the user starting with the least certain superpixel, but having the UI checking and skipping over those superpixels that are already labeled by the user.

**Comment by manthey** [comment]
The complexity for the UI is that labels are added, so we have to know whether the labels were present at the start of the labeling epoch; this means that the UI would need to preserve this information the first time any new labeling is done (or read the previous epoch to determine what the state was before this epoch).  Duplicating the labeling information (or the flag for if something is labeled) as we create the new epoch moves that bookkeeping to this code rather than the UI (which is maybe not a sufficient argument to do it).  Looping in @bnmajor so she can opine on this, too.

**Comment by Leengit** [comment]
> we have to know whether the labels were present at the start of the labeling epoch

Perhaps it doesn't matter when the superpixel was labeled.  If at the time we are doing the guiding a superpixel has been labeled then we don't offer it to the user for (re-)labeling, regardless of whether it was labeled before or after the certainties were computed.

**Comment by Leengit** [comment]
I don't know _when_ the UI decides what superpixels to guide the user to.  Perhaps this relates back to what you are saying.

If we have a filter that checks for the presence of an existing label how often do we apply it?  For example, if the user is doing guided labeling, takes a break to do some painting or reviewing, and then goes back to guided labeling ... should we reapply the filter when the user switches back to guided labeling ... because some superpixels may have been labeled (or unlabeled) during the break ... or will the user expect that the set of superpixels that were there before will still be there regardless of the intervening painting and reviewing?

**Comment by Leengit** [comment]
In response to this issue, I'll make changes to `al_bench` so that `batchbald` doesn't waste its selected samples by considering already labeled samples.  The already labeled samples will instead be rated the way all samples not selected by `batchbald` are, as shifted `confidence` scores.  This addresses the "waste" issue for `batchbald`.

It doesn't address the UI issue, but we need input from Lee C. and Jeff G. on that.  Which superpixels should not be presented for guided labeling even if the certainty (e.g., `confidence`, `margin`, `negative_entropy`, or `batchbald` score) is quite low?  The list of excluded superpixels almost surely includes superpixels that have been labeled (and unchanged) since the time of the most recent training, but it is less clear whether superpixels that have had their labels added, changed, or removed since that training should be included in guided labeling.

**Comment by Leengit** [comment]
With Pull Request #20, we are excluding all samples that `SuperpixelClassification` receives with labels, which is the correct behavior except possibly in some edge cases where labels are changed between training and sample evaluation.  If feedback from Lee C. and Jeff G. wants to change which samples are excluded, we can do that with a subsequent pull request.
